modelo/app/urls.py
from django.urls import path
from django.urls.conf import path

from django import urls
from django.db import router
from django.urls import include, path

from app.models import Producto
from .views import *
from rest_framework import routers

from app.views import preparacion,encamino,entregado,eliminarsoporte,listadosoporte,soporte,modificarpedidos,listapedidosadm,datoseg,seguimiento,comprar,eliminarproductocarrito,cambiarpassword,registro,perfilusuario,crearperfil,index,perro,roedor,gatos,aves,anfibios,quienes,listado,crear,modificar,eliminar,perfil,listaproductos,modificarproductos,eliminarproductos,crearproductos,cart_add,cantidad,carrito

router = routers.DefaultRouter()
router.register('Productos', ProductoViewSet)
router.register('Pedidos', PedidoViewSet)
urlpatterns = [
    path('', index, name='index'),
    path('roedor', roedor, name='roedor'),
    path('perro', perro, name='perro'),
    path('gatos', gatos, name='gatos'),
    path('aves', aves, name='aves'),
    path('anfibios', anfibios, name='anfibios'),
    path('quienes', quienes, name='quienes'),
    path('listado/',listado,name="listado"),
    path('crear/',crear,name="crear"),
    path('modificar/<id>',modificar,name="modificar"),
    path('eliminar/<id>',eliminar,name="eliminar"),
    path('cambiarpassword/',cambiarpassword,name="cambiarpassword"),
    path('registro/',registro,name="registro"),
    path('perfilusuario/',perfilusuario,name="perfilusuario"),
    path('perfil/',perfil,name="perfil"),
    path('listaproductos/',listaproductos,name="listaproductos"),
    path('modificarproductos/<id>',modificarproductos,name="modificarproductos"),
    path('eliminarproductos/<id>',eliminarproductos,name="eliminarproductos"),
    path('crearproductos/',crearproductos,name="crearproductos"),

    path('cart_add/<id>/<precio>', cart_add, name='cart_add'),
    path('cantidad',cantidad,name='cantidad'),
    path('carrito',carrito,name='carrito'),
    path('eliminarproductocarrito/<id>',eliminarproductocarrito,name='eliminarproductocarrito'),
    path('comprar/<id>/',comprar,name='comprar'),
    path('seguimiento/<id>',seguimiento,name='seguimiento'),
    path('datoseg/<id>/',datoseg,name='datoseg'),
    path('listapedidosadm',listapedidosadm,name='listapedidosadm'),
    path('modificarpedidos/<id>/',modificarpedidos,name='modificarpedidos'),
    path('soporte', soporte, name="soporte"),
    path('listadosoporte', listadosoporte, name="listadosoporte"),
    path('eliminarsoporte/<id>',eliminarsoporte,name="eliminarsoporte"),

    path('preparacion',preparacion,name="preparacion"),
    path('encamino',encamino,name="encamino"),
    path('entregado',entregado,name="entregado"),
    

    path('crearperfil',crearperfil,name="crearperfil"),

    path('api/', include(router.urls)),
    
]

modelo/modelo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

if settings.DEBUG==True:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

modelo/app/models.py
from django.db import models
from django.forms import CharField
from distutils.command.upload import upload
from asyncio.windows_events import NULL
from datetime import datetime
# Create your models here.
estado_pedido = [
    (1, 'Preparacion'),
    (2, 'En reparto'),
    (3, 'Entregado'),
]

class Categoria(models.Model):
    id=models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Cliente(models.Model):
    nombreusuario=models.CharField(primary_key=True,max_length=50)
    rut=models.CharField(max_length=10)
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    mail=models.EmailField()
    suscriptor=models.BooleanField()
    
    
    
    def __str__(self):
        return "" + self.rut + " - " + self.nombre

class Producto(models.Model):
    id=models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=50)
    precio=models.IntegerField(("Precio"))
    cantidad=models.IntegerField(("Cantidad"))
    categoria=models.ForeignKey(Categoria, on_delete=models.PROTECT)
    imagen=models.ImageField(upload_to='productoimg')
    def __str__(self):
        return self.nombre 


class Pedido(models.Model):
    id=models.AutoField(primary_key=True)
    nomusuario=models.CharField( max_length=50,default=0)
    fecha=models.DateField()
    estado=models.IntegerField(choices=estado_pedido,default=1)
    direccion=models.CharField(max_length=50)
    producto=models.ManyToManyField(Producto, through='Detalle')

    

    
class Detalle(models.Model):
    producto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    pedido= models.ForeignKey(Pedido, on_delete=models.CASCADE)
    cantidad=models.IntegerField()

class Carrito(models.Model):
    id=models.AutoField(primary_key=True)
    idusuario=models.CharField( max_length=50)
    idprod=models.CharField( max_length=50)
    candtidad=models.IntegerField()
    precio=models.IntegerField(default=0)
    nomproduc=models.CharField(max_length=50,default=0)
    def __str__(self):
        return self.idprod

class Soporte(models.Model):
    id=models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    asunto = models.CharField(max_length=50)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

modelo/app/templates/app/anfibios.html
{% extends 'app/base.html' %}
{% load static %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/pez.png' %}"  width="1920" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-3 g-4 pt-3">
        {% for anfibio in anfibios  %}
        <div class="col">
            <div class="card">
                <img src="{{anfibio.imagen.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{anfibio.nombre}}</h5>
                    <p class="card-text">Precio: ${{anfibio.precio}}</p>
                </div>
            </div>
            <div class="mt-1"><a href="{% url 'cart_add' anfibio.id anfibio.precio %}"><button type="button" class="btn btn-info">Añadir al Carrito</button></div></a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock%}

modelo/app/templates/app/aves.html
{% extends 'app/base.html' %}
{% load static %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/ave.png' %}" width="1920" height="150" style=" max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-3 g-4 pt-3">
        {% for ave in aves  %}
        <div class="col">
            <div class="card">
                <img src="{{ave.imagen.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ave.nombre}}</h5>
                    <p class="card-text">Precio: ${{ave.precio}}</p>
                </div>
            </div>
            <div class="mt-1"><a href="{% url 'cart_add' ave.id ave.precio %}"><button type="button" class="btn btn-info">Añadir al Carrito</button></div></a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock%}

modelo/app/templates/app/carrito.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags%}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid row" >
    <div class="">
        <div class="col-sm-1">

        </div>
        <div class="col-sm-12 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <h1>Carrito</h1>
                <form action="" method="POST" enctype="multipart/form-data">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre producto</th>
                            <th>Cantidad</th>
                            <th>Precio</th>

                            
                        </tr>
                    </thead>
                    <tbody>
                        {% for car in carritos  %}
                        <tr>
                            <td>{{car.nomproduc}}</td>
                            <td>{{car.candtidad}}</td>
                            <td>{{car.precio}}</td>
                            <td>
                                <a href="{% url 'eliminarproductocarrito' car.id %}" class="btn btn-danger btn-sm" role="button">Eliminar Producto</a>
                                <a href="{% url 'comprar' car.id  %}" class="btn btn-success btn-sm" role="button">Comprar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <h1>total: {{total}}</h1>
            </div>
        </div>
        <div class="col-sm-1">

        </div>
    </div>
</div>

{% endblock%}

modelo/app/templates/app/crear.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}
<div class="container-fluid row" >
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <h4>Agregar Personas</h4>
                <hr>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ frm|crispy }}
        
                    <input type="submit" value="Guardar" class="btn btn-success">
                </form>

            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>



{% endblock%}

modelo/app/templates/app/crearproductos.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags%}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}

{% block contenido %}



<div class="container-fluid row" >
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <h4>Agregar Productos</h4>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
    
    
                    <input type="submit" value="Guardar" class="btn btn-outline-success btn-block mt-4">
                </form>

            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>

{% endblock contenido %}

modelo/app/templates/app/eliminar.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid row" >
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <form action="" method="POST">
                    {% csrf_token %}
                        <p>Esta seguro que desea eliminar a:</p>
                        <p>{{cliente.nombreusuario}}</p>
                        <p>{{cliente.nombre}} {{cliente.apellido}}</p>
                        <input type="submit" value="Eliminar" class="btn btn-danger">
        
                   </form>

            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>




{% endblock contenido %}

modelo/app/templates/app/eliminarproductos.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid row" >
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <form action="" method="POST">
                    {% csrf_token %}
                        <p>Esta seguro que desea eliminar a:</p>
                        <p>{{producto.nombre}}</p>
                        <p>{{producto.precio}} {{producto.cantidad}}</p>
                        <input type="submit" value="Eliminar" class="btn btn-danger">
        
                   </form>

            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>




{% endblock contenido %}

modelo/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/gatoprecioso.jpg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}

{% block contenido %}
<div class="mt-3">
    <div class=" row-cols-md-2">

    </div>

    <div class=" row-cols-md-8">
        <div id="demo" class="carousel slide" data-bs-ride="carousel">

            <!-- Indicators/dots -->
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
            </div>

                <!-- The slideshow/carousel -->
                <div class="carousel-inner responsive">
                    <div class="carousel-item active">
                        <a href="{% url 'perro' %}"><img src="{% static 'app/Img/oferta.png' %}" alt="Los Angeles" class="d-block mx-auto "></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'perro' %}"></a><img src="{% static 'app/Img/carrusel.png' %}" alt="Chicago" class="d-block mx-auto"></a>
                    </div>
                    <div class="carousel-item">
                        <a href="{% url 'quienes' %}"></a><img src="{% static 'app/Img/quienes_somos.png' %}" alt="New York"
                            class="d-block mx-auto "></a>
                    </div>
                </div>

                <!-- Left and right controls/icons -->
                <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </button>
    </div>

    <div class="row-cols-md-2">

    </div>

</div>
{% endblock contenido %}

modelo/app/templates/app/modificar.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid row">
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <script>
                    $(document).ready(function () {
                        $("#id_nombreusuario").attr("readonly", true);
                    });

                </script>
                <script>
                    $(document).ready(function () {
                        $("#id_rut").attr("readonly", true);
                    });

                </script>
                <div class="m-3 p-5">
                    <div class="">
                        <div class=" ">

                        </div>
                        <div class=" ">
                            
                            <h4>Modificar Persona Usuario {{id}}</h4>
                            <hr>
                            <form action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ frm|crispy }}

                                <input type="submit" value="Modificar" class="btn btn-warning">
                            </form>

                        </div>
                    </div>
                    <div class="col-sm-3">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock contenido %}

modelo/app/templates/app/perfil.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}

{% block contenido %}

<div class="container-fluid row" >
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <h1 class="text-center">👤Perfil de Usuario</h1>
            <h4>Nombre de Usuario: {{user.username}}</h4>
            {% for per in perfil  %}
            <div class="">
                <h4>Nombre: {{per.nombre}}</h4>
                <h4>Apellido: {{per.apellido}}</h4>
                <h4>Correo: {{per.mail}}</h4>
            </div>
            {% endfor %}
            <form action="" method="post">
                <div><a href="{% url 'cambiarpassword' %}" button type="button" class="btn btn-warning"></button>Cambiar contraseña</a></div>
                <h4 class="text-center">Listado de Pedidos: </h4>


                    <table class="table">
                        <thead>
                            <tr>
                                <th>fecha</th>
                                <th>estado</th>
                                <th>dirección</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {%for ped in pedido%}
                            <tr>

                                <td>{{ped.fecha}}</td>
                                <td>{{ped.estado}}</td>
                                <td>{{ped.direccion}}</td>
                                <td>
                                <td>
                                    <div><a href="{% url 'seguimiento' ped.id   %}" button type="button" class="btn btn-success"></button>Seguimiento de productos</a></div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>


        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>


{% endblock contenido %}

modelo/app/templates/app/quienes.html
{% extends 'app/base.html' %}
{% load static %}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container fondo_sombra p-5 my-5 bg-dark text-white">
    <h1 class="text-center"> ¿Quienes Somos?
        <h6 class="text-center quienessomos_fondo">Somos una tienda dedicada a la atención de los peluditos de la
            casa. Ofrecemos venta de alimentos, accesorios y productos de higiene para mascotas.

            Descubre la mayor variedad de productos, alimentos y accesorios disponibles para ti.

            Ademas permitimos la suscripción a nuetra tienda con un aporte voluntario a una fundación sin fines de
            lucro, como agradecimiento a las buenas costumbres te descontaremos el 5% en tus compras

        </h6>

        <div class="d-grid">

            <a class="d-grid quienessomos_fondo" href="{% url 'perfil'%}"><button type="button"
                    class="btn btn-success btn-block">Suscribirse</button></a>


        </div>
    </div>

</h4>
</div>


{% endblock%}

modelo/app/templates/app/seguimiento2.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags%}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-3 g-4 pt-3">
        <div class="col">
            <div class="card">
                <img src="{% static 'app/Img/collar.png' %}" class="card-img-top" alt="collar de perro">
            </div>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <p class="text-center text-white">Su paquete está en reparto.</p></div></div>
        </div>
        
    </div>
    
</div>




{% endblock%}

modelo/app/templates/app/seguimiento3.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags%}

{% block img %}
<div class="">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg' %}" style="max-width: 100%;">
    </div>
</div>
{% endblock %}
{% block contenido %}

<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-3 g-4 pt-3">
        <div class="col">
            <div class="card">
                <img src="{% static 'app/Img/collar.png' %}" class="card-img-top" alt="collar de perro">
            </div>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <p class="text-center text-white">Su paquete está en entregado.</p></div></div>
        </div>
        
    </div>
    
</div>




{% endblock%}

modelo/app/templates/app/soporte.html
{% extends 'app/base.html' %}

{% load static %}

{% block imagensuperior %}
<div class="row ">
    <div class="col-12">
        <img src="{% static 'app/Img/perrioMejorado.svg'%}" style="max-width: 100%;">
    </div>

{% endblock %}
{% load crispy_forms_tags %}
{% block contenido %}




<div class="container-fluid row" >
    <div class=" row ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5 m-3 p-3 border shadow rounded" id="bglistado">
            <div class="container mt-3">
                <h4>Formulario soporte</h4>
                <hr>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
        
                    <input type="submit" value="Guardar" class="btn btn-success">
                </form>
                {{mensaje}}
            </div>
        </div>
        <div class="col-sm-3">

        </div>
    </div>
</div>






    {% endblock %}